# -*- coding: utf-8 -*-
"""
自動化部署腳本 - 一鍵部署新服務
只需在 services.json 添加新服務，運行此腳本即可自動配置所有內容
"""

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

def load_services():
    """載入服務配置"""
    services_file = ROOT / "services.json"
    with open(services_file, 'r', encoding='utf-8') as f:
        return json.load(f)['services']

def generate_nginx_config(services):
    """生成 Nginx 配置"""
    config = """# Auto-generated Nginx Configuration
# Generated by auto_deploy.py - DO NOT EDIT MANUALLY
# Edit services.json and run: python scripts/auto_deploy.py

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # 日誌格式
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log warn;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    # WebSocket 支援
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

"""

    # 為每個服務生成 server block
    for service in services:
        if not service.get('enabled', True):
            continue
        
        subdomain = service['subdomain']
        domain = service['domain']
        target = service['target']
        
        if subdomain:
            server_name = f"{subdomain}.{domain}"
        else:
            server_name = f"{domain} www.{domain}" if service['name'] == 'Portal' else domain
        
        config += f"""    # {service['name']} - {service['description']}
    server {{
        listen 80;
        server_name {server_name};

        location / {{
            proxy_pass http://{target};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket 支援
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            # 超時設定
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }}
    }}

"""

    config += "}\n"
    return config

def generate_cloudflare_config(services):
    """生成 Cloudflare Tunnel 配置說明"""
    config = {
        "ingress": []
    }
    
    for service in services:
        if not service.get('enabled', True):
            continue
        
        subdomain = service['subdomain']
        domain = service['domain']
        
        if subdomain:
            hostname = f"{subdomain}.{domain}"
        else:
            hostname = domain
        
        config["ingress"].append({
            "hostname": hostname,
            "service": "http://gateway:80",
            "originRequest": {}
        })
    
    # 添加默認路由
    config["ingress"].append({
        "service": "http://gateway:80"
    })
    
    config["warp-routing"] = {"enabled": False}
    
    return config

def generate_portal_config(services):
    """生成 Portal 服務配置"""
    portal_services = {}
    
    for service in services:
        if not service.get('enabled', True) or service['name'] in ['Portal', 'Portal WWW']:
            continue
        
        subdomain = service['subdomain']
        domain = service['domain']
        
        service_id = subdomain if subdomain else 'main'
        
        portal_services[service_id] = {
            "name": service['name'],
            "url": f"https://{subdomain}.{domain}" if subdomain else f"https://{domain}",
            "health": f"https://{subdomain}.{domain}/health" if subdomain else f"https://{domain}/health",
            "local": f"http://localhost:{service['port']}/health",
            "icon": subdomain or "home",
            "color": "blue",
            "description": service['description']
        }
    
    return portal_services

def main():
    print("🚀 自動化部署腳本\n")
    
    # 1. 載入服務配置
    print("📋 載入服務配置...")
    services = load_services()
    enabled_services = [s for s in services if s.get('enabled', True)]
    print(f"✅ 找到 {len(enabled_services)} 個啟用的服務\n")
    
    # 2. 生成 Nginx 配置
    print("🔧 生成 Nginx 配置...")
    nginx_config = generate_nginx_config(services)
    nginx_file = ROOT / "gateway" / "nginx.conf"
    nginx_file.write_text(nginx_config, encoding='utf-8')
    print(f"✅ 已生成: {nginx_file}\n")
    
    # 3. 生成 Cloudflare 配置說明
    print("☁️  生成 Cloudflare Tunnel 配置...")
    cf_config = generate_cloudflare_config(services)
    cf_file = ROOT / "cloudflare_tunnel_config.json"
    cf_file.write_text(json.dumps(cf_config, indent=2, ensure_ascii=False), encoding='utf-8')
    print(f"✅ 已生成: {cf_file}\n")
    
    # 4. 生成 Portal 配置
    print("🌐 生成 Portal 服務配置...")
    portal_config = generate_portal_config(services)
    portal_file = ROOT / "portal" / "services_config.json"
    portal_file.write_text(json.dumps(portal_config, indent=2, ensure_ascii=False), encoding='utf-8')
    print(f"✅ 已生成: {portal_file}\n")
    
    # 5. 顯示需要在 Cloudflare 添加的域名
    print("=" * 60)
    print("📝 需要在 Cloudflare Zero Trust 添加的域名:")
    print("=" * 60)
    for service in enabled_services:
        subdomain = service['subdomain']
        domain = service['domain']
        hostname = f"{subdomain}.{domain}" if subdomain else domain
        print(f"  ✅ {hostname:30} → gateway:80")
    print("=" * 60)
    
    print("\n🎯 下一步操作:")
    print("  1. 重啟 Gateway: docker compose restart gateway")
    print("  2. 在 Cloudflare Zero Trust 添加上述域名")
    print("  3. 或運行: python scripts/sync_cloudflare.py (需要 API Token)")
    print("\n✨ 完成！")

if __name__ == "__main__":
    main()
